### ISSUE TITLE
Can not load node on windows

### ISSUE THREAD

**Issue by ultimatech-cn** [Smuzzies/comfyui_chatbox_overlay#1]
Copy py file to ComfyUI\customer_node\  directory or clone from git.  Both got error on console as below

> Traceback (most recent call last):
>   File "C:\DEV\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 879, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 1016, in get_code
>   File "<frozen importlib._bootstrap_external>", line 1073, in get_data
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\DEV\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyuiEasyToUseText2Gif_v1\\__init__.py'
> 
> Cannot import C:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyuiEasyToUseText2Gif_v1 module for custom nodes: [Errno 2] No such file or directory: 'C:\\DEV\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyuiEasyToUseText2Gif_v1\\__init__.py'
> Traceback (most recent call last):
>   File "C:\DEV\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 879, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 1016, in get_code
>   File "<frozen importlib._bootstrap_external>", line 1073, in get_data
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\DEV\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_chatbox_overlay\\__init__.py'

Any suggestion?

**Comment by ultimatech-cn** [comment]
solved the problem.
move the file to \ComfyUI\custom_nodes\ directory.

**Comment by gonzalu** [comment]
I can;t use ANY fonts... all fonts generate errors.. :(
